CREATE TABLE morewords (
  id INTEGER PRIMARY KEY,
  word VARCHAR(30),
  hint VARCHAR(255),
  category VARCHAR(30)
);

INSERT INTO morewords (id, word, hint, category) VALUES 
(1, 'elephant', 'A large mammal with a trunk.', 'animals'),
(2, 'leonardo dicaprio', 'An actor known for his roles in Titanic and Inception.', 'celebrities'),
(3, 'inception', 'A movie about dreams within dreams.', 'movies'),
(4, 'sushi', 'A popular Japanese dish made with rice and fish.', 'food'),
(5, 'beethoven', 'A famous composer known for his symphonies.', 'music'),
(6, 'amazon', 'The largest river by discharge volume in the world.', 'geography'),
(7, 'napoleon', 'French military leader who became emperor.', 'history'),
(8, 'einstein', 'A physicist known for the theory of relativity.', 'science'),
(9, 'basketball', 'A sport played with a hoop and ball.', 'sports'),
(10, 'mario', 'A popular video game character created by Nintendo.', 'video games'),
(11, 'pizza', 'A popular dish consisting of dough topped with cheese and other ingredients.', 'food'),
(12, 'lion', 'The king of the jungle.', 'animals'),
(13, 'star wars', 'A popular space-themed movie franchise.', 'movies'),
(14, 'madonna', 'A famous pop singer known for hits like "Like a Virgin".', 'music'),
(15, 'himalayas', 'The highest mountain range in the world.', 'geography'),
(16, 'newton', 'A physicist known for the laws of motion.', 'science'),
(17, 'football', 'A sport played with an oval-shaped ball.', 'sports'),
(18, 'zelda', 'A popular video game series from Nintendo.', 'video games'),
(19, 'socrates', 'An ancient Greek philosopher known for the Socratic method.', 'history'),
(20, 'tiger', 'A large feline known for its stripes.', 'animals'),
(21, 'giraffe', 'The tallest animal in the world with a long neck.', 'animals'),
(22, 'meryl streep', 'A renowned actress with three Academy Awards.', 'celebrities'),
(23, 'avatar', 'A movie directed by James Cameron set in a lush alien world.', 'movies'),
(24, 'tacos', 'A traditional Mexican dish consisting of folded tortillas.', 'food'),
(25, 'bach', 'A composer known for his Brandenburg Concertos.', 'music'),
(26, 'sahara', 'The largest hot desert in the world.', 'geography'),
(27, 'alexander the great', 'A historical figure known for conquering a vast empire.', 'history'),
(28, 'marie curie', 'A physicist and chemist who discovered radioactivity.', 'science'),
(29, 'soccer', 'A popular sport played with a round ball and goals.', 'sports'),
(30, 'sonic', 'A blue hedgehog and video game character known for speed.', 'video games'),
(31, 'cake', 'A sweet dessert often served at celebrations.', 'food'),
(32, 'kangaroo', 'A marsupial from Australia that hops.', 'animals'),
(33, 'the godfather', 'A classic movie about a crime family.', 'movies'),
(34, 'taylor swift', 'A famous singer-songwriter known for hits like "Shake It Off".', 'music'),
(35, 'mississippi', 'The second-longest river in the United States.', 'geography'),
(36, 'galileo', 'A scientist known for his work on telescopes and astronomy.', 'science'),
(37, 'rugby', 'A sport similar to American football with more physical contact.', 'sports'),
(38, 'minecraft', 'A sandbox video game where players can build and explore.', 'video games'),
(39, 'julius caesar', 'A Roman general and leader who was famously assassinated.', 'history'),
(40, 'dolphin', 'A highly intelligent marine mammal.', 'animals'),
(41, 'koala', 'An Australian marsupial known for its diet of eucalyptus leaves.', 'animals'),
(42, 'morgan freeman', 'An actor with a distinctive deep voice, known for his role in The Shawshank Redemption.', 'celebrities'),
(43, 'the matrix', 'A science fiction movie that explores a virtual reality world.', 'movies'),
(44, 'pasta', 'An Italian staple food made from wheat and water.', 'food'),
(45, 'mozart', 'A prolific composer known for his symphonies and operas.', 'music'),
(46, 'antarctica', 'The southernmost continent, known for its ice and cold temperatures.', 'geography'),
(47, 'abraham lincoln', 'The 16th President of the United States who led during the Civil War.', 'history'),
(48, 'isaac newton', 'A scientist who formulated the laws of motion and universal gravitation.', 'science'),
(49, 'tennis', 'A sport played with a racket and a small yellow ball.', 'sports'),
(50, 'pac-man', 'An iconic video game character known for eating dots.', 'video games'),
(51, 'ice cream', 'A frozen dessert made from cream and sugar.', 'food'),
(52, 'camel', 'A desert animal with one or two humps.', 'animals'),
(53, 'jurassic park', 'A movie franchise about dinosaurs brought back to life.', 'movies'),
(54, 'beyonce', 'A famous singer known for her powerful voice and performances.', 'music'),
(55, 'andes', 'A mountain range in South America, running through several countries.', 'geography'),
(56, 'charles darwin', 'A scientist known for his theory of evolution by natural selection.', 'science'),
(57, 'hockey', 'A sport played on ice with sticks and a puck.', 'sports'),
(58, 'tetris', 'A classic puzzle video game with falling blocks.', 'video games'),
(59, 'cleopatra', 'An Egyptian queen known for her beauty and relationships with Roman leaders.', 'history'),
(60, 'polar bear', 'A large bear species found in the Arctic.', 'animals'),
(61, 'orangutan', 'An arboreal great ape with long arms and reddish fur.', 'animals'),
(62, 'jennifer lawrence', 'An actress known for her role in The Hunger Games.', 'celebrities'),
(63, 'harry potter', 'A movie series about a young wizard and his adventures.', 'movies'),
(64, 'croissant', 'A flaky, buttery French pastry.', 'food'),
(65, 'chopin', 'A composer known for his piano pieces and nocturnes.', 'music'),
(66, 'ganges', 'A major river in India, considered sacred.', 'geography'),
(67, 'george washington', 'The first President of the United States.', 'history'),
(68, 'spongebob squarepants', 'Yellow spong who lives in a pineapple under the sea', 'celebrities'),
(69, 'volleyball', 'A sport played with a ball over a net.', 'sports'),
(70, 'halo', 'A popular video game series featuring a futuristic soldier.', 'video games'),
(71, 'brownie', 'A dense, chocolatey dessert.', 'food'),
(72, 'penguin', 'A flightless bird that lives in cold climates.', 'animals'),
(73, 'jaws', 'A thriller movie about a man-eating shark.', 'movies'),
(74, 'michael jackson', 'A famous pop singer known as the "King of Pop".', 'music'),
(75, 'alps', 'A major mountain range in Europe.', 'geography'),
(76, 'thomas edison', 'An inventor known for the light bulb and phonograph.', 'science'),
(77, 'baseball', 'A sport played with a bat, a ball, and bases.', 'sports'),
(78, 'fortnite', 'A popular battle royale video game.', 'video games'),
(79, 'catherine the great', 'An influential Russian empress in the 18th century.', 'history'),
(80, 'grizzly bear', 'A large bear species found in North America.', 'animals'),
(81, 'octopus', 'A sea creature with eight tentacles.', 'animals'),
(82, 'robert downey jr.', 'An actor best known for his role as Iron Man.', 'celebrities'),
(83, 'titanic', 'A movie about a tragic shipwreck.', 'movies'),
(84, 'cheeseburger', 'A hamburger topped with cheese.', 'food'),
(85, 'vivaldi', 'A composer known for "The Four Seasons".', 'music'),
(86, 'nile', 'The longest river in Africa.', 'geography'),
(87, 'martin luther king jr.', 'A civil rights leader known for his "I Have a Dream" speech.', 'history'),
(88, 'stephen hawking', 'A physicist known for his work on black holes.', 'science'),
(89, 'cricket', 'A sport played with a bat and ball, popular in many countries.', 'sports'),
(90, 'legend of zelda', 'A classic video game series featuring Link.', 'video games'),
(91, 'apple pie', 'A classic American dessert.', 'food'),
(92, 'chimpanzee', 'An intelligent primate closely related to humans.', 'animals'),
(93, 'blade runner', 'A science fiction movie set in a dystopian future.', 'movies'),
(94, 'adele', 'A singer known for her powerful voice and ballads.', 'music'),
(95, 'rocky mountains', 'A major mountain range in North America.', 'geography'),
(96, 'queen elizabeth ii', 'The longest-reigning British monarch.', 'history'),
(97, 'richard feynman', 'A physicist known for his work in quantum mechanics.', 'science'),
(98, 'field hockey', 'A team sport played on grass with sticks and a ball.', 'sports'),
(99, 'super mario', 'A classic video game featuring an Italian plumber.', 'video games'),
(100, 'lasagna', 'An Italian dish made with layers of pasta, cheese, and meat sauce.', 'food'),
(101, 'parrot', 'A colorful bird known for its ability to mimic sounds.', 'animals'),
(102, 'the terminator', 'A movie franchise about time-traveling cyborgs.', 'movies'),
(103, 'elvis presley', 'A famous rock and roll singer known as "The King".', 'music'),
(104, 'yellowstone', 'A national park known for geysers and hot springs.', 'geography'),
(105, 'benjamin franklin', 'A Founding Father of the United States known for his experiments with electricity.', 'history'),
(106, 'niels bohr', 'A physicist who made significant contributions to atomic theory.', 'science'),
(107, 'golf', 'A sport where players aim to hit a ball into holes with as few strokes as possible.', 'sports'),
(108, 'assassins creed', 'A popular video game franchise involving historical settings.', 'video games'),
(109, 'tiramisu', 'An Italian dessert made with layers of coffee-soaked ladyfingers and mascarpone cheese.', 'food'),
(110, 'red panda', 'A small mammal with a bushy tail, native to the Himalayas.', 'animals');

