CREATE table wordslist (
  id INTEGER PRIMARY KEY,
  word VARCHAR(30),
  hint VARCHAR(255)
);

INSERT INTO wordslist (id, word, hint) VALUES 
  (1, 'guitar', 'A musical instrument with strings.'),
  (2, 'oxygen', 'A colorless, odorless gas essential for life.'),
  (3, 'mountain', 'A large natural elevation of the Earths surface.'),
  (4, 'painting', 'An art form using colors on a surface to create images or expression.'),
  (5, 'astronomy', 'The scientific study of celestial objects and phenomena.'),
  (6, 'football', 'A popular sport played with a spherical ball.'),
  (7, 'chocolate', 'A sweet treat made from cocoa beans.'),
  (8, 'butterfly', 'An insect with colorful wings and a slender body.'),
  (9, 'history', 'The study of past events and human civilization.'),
  (10, 'pizza', 'A savory dish consisting of a round, flattened base with toppings.'),
  (11, 'jazz', 'A genre of music characterized by improvisation and syncopation.'),
  (12, 'camera', 'A device used to capture and record images or videos.'),
  (13, 'diamond', 'A precious gemstone known for its brilliance and hardness.'),
  (14, 'adventure', 'An exciting or daring experience.'),
  (15, 'science', 'The systematic study of the structure and behavior of the physical and natural world.'),
  (16, 'bicycle', 'A human-powered vehicle with two wheels.'),
  (17, 'sunset', 'The daily disappearance of the sun below the horizon.'),
  (18, 'coffee', 'A popular caffeinated beverage made from roasted coffee beans.'),
  (19, 'dance', 'A rhythmic movement of the body often performed to music.'),
  (20, 'galaxy', 'A vast system of stars, gas, and dust held together by gravity.'),
  (21, 'orchestra', 'A large ensemble of musicians playing various instruments.'),
  (22, 'volcano', 'A mountain or hill with a vent through which lava, rock fragments, hot vapor, and gas are ejected.'),
  (23, 'novel', 'A long work of fiction, typically with a complex plot and characters.'),
  (24, 'sculpture', 'A three-dimensional art form created by shaping or combining materials.'),
  (25, 'symphony', 'A long musical composition for a full orchestra, typically in multiple movements.'),
  (26, 'architecture', 'The art and science of designing and constructing buildings.'),
  (27, 'ballet', 'A classical dance form characterized by precise and graceful movements.'),
  (28, 'astronaut', 'A person trained to travel and work in space.'),
  (29, 'waterfall', 'A cascade of water falling from a height.'),
  (30, 'technology', 'The application of scientific knowledge for practical purposes.'),
  (31, 'rainbow', 'A meteorological phenomenon that is caused by reflection, refraction, and dispersion of light.'),
  (32, 'universe', 'All existing matter, space, and time as a whole.'),
  (33, 'piano', 'A musical instrument played by pressing keys that cause hammers to strike strings.'),
  (34, 'vacation', 'A period of time devoted to pleasure, rest, or relaxation.'),
  (35, 'rainforest', 'A dense forest characterized by high rainfall and biodiversity.'),
  (36, 'theater', 'A building or outdoor area in which plays, movies, or other performances are staged.'),
  (37, 'telephone', 'A device used to transmit sound over long distances.'),
  (38, 'language', 'A system of communication consisting of words, gestures, and syntax.'),
  (39, 'desert', 'A barren or arid land with little or no precipitation.'),
  (40, 'sunflower', 'A tall plant with a large yellow flower head.'),
  (41, 'fantasy', 'A genre of imaginative fiction involving magic and supernatural elements.'),
  (42, 'telescope', 'An optical instrument used to view distant objects in space.'),
  (43, 'breeze', 'A gentle wind.'),
  (44, 'oasis', 'A fertile spot in a desert where water is found.'),
  (45, 'photography', 'The art, process, or practice of creating images by recording light or other electromagnetic radiation.'),
  (46, 'safari', 'An expedition or journey, typically to observe wildlife in their natural habitat.'),
  (47, 'planet', 'A celestial body that orbits a star and does not produce light of its own.'),
  (48, 'river', 'A large natural stream of water flowing in a channel to the sea, a lake, or another such stream.'),
  (49, 'tropical', 'Relating to or situated in the region between the Tropic of Cancer and the Tropic of Capricorn.'),
  (50, 'mysterious', 'Difficult or impossible to understand, explain, or identify.'),
  (51, 'enigma', 'Something that is mysterious, puzzling, or difficult to understand.'),
  (52, 'paradox', 'A statement or situation that contradicts itself or defies intuition.'),
  (53, 'puzzle', 'A game, toy, or problem designed to test ingenuity or knowledge.'),
  (54, 'whisper', 'To speak very softly or quietly, often in a secretive manner.'),
  (55, 'shadow', 'A dark area or shape produced by an object blocking the light.'),
  (56, 'secret', 'Something kept hidden or unknown to others.'),
  (57, 'curiosity', 'A strong desire to know or learn something.'),
  (58, 'unpredictable', 'Not able to be foreseen or known beforehand; uncertain.'),
  (59, 'obfuscate', 'To confuse or bewilder someone; to make something unclear or difficult to understand.'),
  (60, 'unveil', 'To make known or reveal something previously secret or unknown.'),
  (61, 'illusion', 'A false perception or belief; a deceptive appearance or impression.'),
  (62, 'moonlight', 'The light from the moon.'),
  (63, 'vibrant', 'Full of energy, brightness, and life.'),
  (64, 'nostalgia', 'A sentimental longing or wistful affection for the past.'),
  (65, 'brilliant', 'Exceptionally clever, talented, or impressive.'),
  (66, 'compass', 'A navigational instrument that shows directions.'),
  (67, 'harmony', 'A pleasing combination of musical notes.'),
  (68, 'sapphire', 'A precious gemstone, typically blue in color.'),
  (69, 'cello', 'A large stringed instrument in the violin family, played with a bow.'),
  (70, 'sorcery', 'The use of magic or supernatural powers.'),
  (71, 'meteor', 'A small body of matter from outer space that enters the earth’s atmosphere.'),
  (72, 'carpentry', 'The skill or work of making things with wood.'),
  (73, 'parachute', 'A device used to slow down an object falling through the air.'),
  (74, 'orchid', 'A type of flowering plant known for its beautiful blooms.'),
  (75, 'sculptor', 'An artist who creates sculptures.'),
  (76, 'twilight', 'The time of day when the sun is below the horizon but the sky is still illuminated.'),
  (77, 'maple', 'A type of tree known for its sap, used to make syrup.'),
  (78, 'cartography', 'The art or science of making maps.'),
  (79, 'biology', 'The scientific study of life and living organisms.'),
  (80, 'ecosystem', 'A community of living organisms and their environment.'),
  (81, 'gravity', 'The force that attracts a body toward the center of the earth.'),
  (82, 'molecule', 'A group of atoms bonded together.'),
  (83, 'amethyst', 'A precious gemstone that is typically violet in color.'),
  (84, 'alchemy', 'A medieval chemical science and speculative philosophy.'),
  (85, 'whirlpool', 'A body of rotating water that can pull objects into its center.'),
  (86, 'autumn', 'The season of the year when leaves fall and temperatures cool.'),
  (87, 'spring', 'The season of the year when plants begin to grow and temperatures warm.'),
  (88, 'blizzard', 'A severe snowstorm with strong winds.'),
  (89, 'hydraulic', 'Operated by or involving the movement or pressure of water or other fluids.'),
  (90, 'eclipse', 'An event where one celestial body obscures another.'),
  (91, 'labyrinth', 'A complex maze with many pathways.'),
  (92, 'celestial', 'Relating to the sky or outer space.'),
  (93, 'equilibrium', 'A state of balance or stability.'),
  (94, 'constellation', 'A group of stars forming a recognizable pattern.'),
  (95, 'reflection', 'The return of light or sound waves from a surface.'),
  (96, 'evaporation', 'The process by which a liquid turns into vapor.'),
  (97, 'fusion', 'The process of joining two or more things together to form a single entity.'),
  (98, 'evolution', 'The gradual development of something, especially from a simple to a more complex form.'),
  (99, 'thunderstorm', 'A storm with thunder and lightning.'),
  (100, 'revolution', 'A fundamental change in the way things are organized or done.');